#!/usr/bin/env python3
"""
step2_baseline.py — does the signal beat random?

Deep OTM options near expiry are lottery tickets. Some fraction reach 25x with
no pattern at all, purely because that's what cheap convex instruments do. A 20%
hit rate means nothing until you know what random entry gives on the SAME
population.

    python3 step2_baseline.py --data dataset.csv
    python3 step2_baseline.py --data dataset.csv --random random_entries.csv

Two modes:

  (a) --random supplied: a file of random-entry outcomes you generated by
      sampling timestamps from the same OTM/DTE population and running the same
      forward scan. This is the real comparison.

  (b) no --random: falls back to an INTERNAL comparison — signal strength
      quartiles against each other, plus the weakest-decile rows as a proxy for
      "barely fired". Weaker evidence, but free, and it still detects the
      failure mode where signal strength ranks nothing.

Reports the full distribution, not just the mean — whether the signal shifts the
whole distribution or only the tail changes what you build next.
"""

import argparse, os, sys
import numpy as np
import pandas as pd
from scipy import stats


def wq(x, w, q):
    """Weighted quantile. Needed because step1 keeps all positives and samples
    negatives — unweighted percentiles describe the sample, not the market."""
    o = np.argsort(x)
    x, w = x[o], w[o]
    c = np.cumsum(w) - 0.5 * w
    c /= w.sum()
    return np.interp(q, c, x)


def dist_summary(x, name, w=None):
    x = np.asarray(x, dtype=float)
    w = np.ones_like(x) if w is None else np.asarray(w, dtype=float)
    ok = np.isfinite(x) & np.isfinite(w)
    x, w = x[ok], w[ok]
    if len(x) == 0:
        return None
    return {
        "name": name, "n": len(x), "mean": np.average(x, weights=w),
        "median": wq(x, w, .50), "p75": wq(x, w, .75), "p90": wq(x, w, .90),
        "p99": wq(x, w, .99), "max": x.max(),
    }


def print_table(rows):
    hdr = f"{'':22}{'n':>8}{'mean':>9}{'median':>9}{'p75':>9}{'p90':>9}{'p99':>9}{'max':>9}"
    print(hdr); print("-" * len(hdr))
    for r in rows:
        if r is None:
            continue
        print(f"{r['name']:22}{r['n']:>8,}{r['mean']:>9.2f}{r['median']:>9.2f}"
              f"{r['p75']:>9.2f}{r['p90']:>9.2f}{r['p99']:>9.2f}{r['max']:>9.1f}")


def hit_rates(peaks, targets=(5, 10, 25, 50, 100), w=None):
    """Weighted so sampled negatives still give the full-data rate."""
    peaks = np.asarray(peaks, dtype=float)
    w = np.ones_like(peaks) if w is None else np.asarray(w, dtype=float)
    ok = np.isfinite(peaks) & np.isfinite(w)
    peaks, w = peaks[ok], w[ok]
    tot = w.sum() or 1.0
    return {t: w[peaks >= t].sum() / tot * 100 for t in targets}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help="output of step1")
    ap.add_argument("--random", default=None,
                    help="random-entry outcomes (csv/json) with a peak-ratio column")
    ap.add_argument("--strength-col", default=None,
                    help="signal strength column (default: auto-detect signalValue)")
    args = ap.parse_args()

    print("=" * 68)
    print("STEP 2 — null baseline: does the signal beat random?")
    print("=" * 68)

    df = (pd.read_parquet(args.data)
          if args.data.endswith(".parquet") or os.path.isdir(args.data)
          else pd.read_csv(args.data))
    if "_w" not in df.columns:
        df["_w"] = 1.0
    peaks = pd.to_numeric(df["_peak"], errors="coerce").dropna()
    print(f"\nsignal rows: {len(peaks):,}")

    sig = dist_summary(peaks, "SIGNAL", w=df.loc[peaks.index, "_w"])
    rows = [sig]
    rnd_peaks = None

    if args.random:
        if args.random.endswith(".parquet"):
            rnd = pd.read_parquet(args.random)
        elif args.random.endswith(".csv"):
            rnd = pd.read_csv(args.random)
        else:
            rnd = pd.read_json(args.random)
        col = next((c for c in rnd.columns
                    if c.lower().replace("_", "") in
                    ("peak", "peakratio", "maxratio", "ratio", "forwardratio")), None)
        if col is None:
            sys.exit(f"ERROR: no peak-ratio column in {args.random}. "
                     f"Columns: {list(rnd.columns)}")
        rnd_peaks = pd.to_numeric(rnd[col], errors="coerce").dropna()
        rows.append(dist_summary(rnd_peaks, "RANDOM"))
        print(f"random rows: {len(rnd_peaks):,}")

    print("\nDISTRIBUTION OF FORWARD PEAK RATIO")
    print_table(rows)

    print("\nHIT RATES (% reaching each multiple)")
    hdr = f"{'':22}" + "".join(f"{str(t)+'x':>10}" for t in (5, 10, 25, 50, 100))
    print(hdr); print("-" * len(hdr))
    hs = hit_rates(peaks, w=df.loc[peaks.index, "_w"])
    print(f"{'SIGNAL':22}" + "".join(f"{hs[t]:>9.1f}%" for t in (5, 10, 25, 50, 100)))
    if rnd_peaks is not None:
        hr = hit_rates(rnd_peaks)
        print(f"{'RANDOM':22}" + "".join(f"{hr[t]:>9.1f}%" for t in (5, 10, 25, 50, 100)))
        print(f"{'LIFT (x)':22}" + "".join(
            f"{(hs[t]/hr[t] if hr[t] > 0 else float('nan')):>10.2f}"
            for t in (5, 10, 25, 50, 100)))

        u = stats.mannwhitneyu(peaks, rnd_peaks, alternative="greater")
        print(f"\nMann-Whitney U (signal > random): p = {u.pvalue:.2e}")
        print("  (tests the WHOLE distribution, not just the mean — robust to "
              "the fat tail)")

        print("\n" + "=" * 68)
        lift25 = hs[25] / hr[25] if hr[25] > 0 else float("nan")
        if not np.isfinite(lift25):
            print("VERDICT: random produced no 25x events — signal lift is "
                  "unbounded but the sample is too small to quantify.")
        elif lift25 >= 2.0 and u.pvalue < 0.01:
            print(f"VERDICT: signal beats random by {lift25:.1f}x at the 25x "
                  f"level, and the whole distribution is shifted.")
            print("         The structure carries real information. Tuning it "
                  "(step 3) is worth doing.")
        elif lift25 >= 1.3:
            print(f"VERDICT: modest edge ({lift25:.1f}x at 25x).")
            print("         Worth tuning — step 3 may find the edge concentrates "
                  "in a subset of conditions.")
        else:
            print(f"VERDICT: signal ≈ random ({lift25:.1f}x at 25x).")
            print("         The signal is selecting little beyond the base "
                  "convexity of cheap OTM options.")
            print("         Still run step 3 — it tests whether CONTEXT "
                  "(tteHours, moneyness) separates the winners,")
            print("         which is a different question from whether the "
                  "pattern does.")
        print("=" * 68)
    else:
        print("\n(no --random file: showing internal strength comparison instead)")

    # ---- internal: does signal strength rank anything? -------------------
    scol = args.strength_col
    if scol is None:
        for c in df.columns:
            if c.lower().replace("_", "") in ("signalvalue", "strength",
                                              "score", "value"):
                scol = c
                break

    if scol and df[scol].notna().sum() > 50:
        print(f"\n\nDOES SIGNAL STRENGTH RANK OUTCOMES?  (column: {scol})")
        print("  Weighted, and split PER SIGNAL — query_lang.js states that")
        print("  signalValue's meaning differs per signal, so pooling them and")
        print("  ranking otm_wall's log values against red_squeeze's ratios")
        print("  compares unlike things.")

        groups = ([(s, g) for s, g in df.groupby("signal", observed=True)]
                  if "signal" in df.columns else [("(all)", df)])

        for sname, g in groups:
            d = g[[scol, "_peak", "_w"]].apply(pd.to_numeric, errors="coerce").dropna()
            if len(d) < 200 or d[scol].nunique() < 10:
                print(f"\n  {sname}: too few rows/values to quintile")
                continue
            try:
                d["q"] = pd.qcut(d[scol], 5, labels=False, duplicates="drop")
            except ValueError:
                print(f"\n  {sname}: not enough distinct values")
                continue

            print(f"\n  {sname}   (n={len(d):,})")
            hdr = (f"  {'quintile':10}{'n':>9}{'strength range':>26}"
                   f"{'25x hit':>10}{'mean peak':>11}")
            print(hdr); print("  " + "-" * (len(hdr) - 2))
            for q, gg in d.groupby("q"):
                w = gg["_w"].to_numpy()
                hit = w[(gg["_peak"] >= 25).to_numpy()].sum() / max(w.sum(), 1e-9)
                mean_pk = np.average(gg["_peak"], weights=w)
                rng_ = f"{gg[scol].min():.3g} - {gg[scol].max():.3g}"
                print(f"  {'Q'+str(int(q)+1):10}{len(gg):>9,}{rng_:>26}"
                      f"{hit*100:>9.2f}%{mean_pk:>11.2f}")

            rho, p = stats.spearmanr(d[scol], d["_peak"])
            verdict = ("ranks essentially NOTHING" if abs(rho) < 0.05 else
                       "has some ranking power" if rho > 0 else
                       "ranks INVERSELY — the score may be backwards")
            print(f"    Spearman rho = {rho:+.3f} (p={p:.1e})  -> {verdict}")

        print("\n  A flat 25x-hit column means the hand-built score is the wrong")
        print("  function of the features. That is what step 3 replaces. It does")
        print("  NOT mean the pattern is worthless.")

    print("\nnext:  python3 step3_tune.py --data " + args.data)


if __name__ == "__main__":
    main()
